name: Build, push to GCR, and deploy
on:
  push:
    branches:    
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and push
    steps:
    - uses: actions/checkout@master
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
    - run: |
        gcloud auth configure-docker
    - name: Build
      run: |        
        docker build -t gcr.io/cdssnc/notify/document-download-api:${GITHUB_SHA::8} -t gcr.io/cdssnc/notify/document-download-api:latest -f ci/Dockerfile .
    - name: Publish
      run: |
        docker push gcr.io/cdssnc/notify/document-download-api:latest && docker push gcr.io/cdssnc/notify/document-download-api:${GITHUB_SHA::8}
    - name: EKS
      uses: docker://gcr.io/cdssnc/aws:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: eks --region ca-central-1 update-kubeconfig --name notification-canada-ca-staging-eks-cluster
    - name: Apply
      uses: docker://gcr.io/cdssnc/aws-kubectl:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: set image deployment.apps/document-download-api document-download-api=gcr.io/cdssnc/notify/document-download-api:${GITHUB_SHA::8} -n=notification-canada-ca --kubeconfig=/github/home/.kube/config
