name: Generate SBOM

on:
  pull_request:
    branches:
      - main
    paths:
      - requirements.txt
      - .github/workflows/generate-sbom.yml
  push:
    branches:
      - main
    paths:
      - requirements.txt
      - .github/workflows/generate-sbom.yml

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Generate app SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@fe8dbcbe2ebef225da0dfc6a3b1d57645a92fcb2 # v1.1.3
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: notification-document-download-api/app
          project_type: python        
