name: CI

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Scan for seekrets
      uses: docker://cdssnc/seekret-github-action
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run tests
      uses: docker://python:3.6-stretch
      with: 
        entrypoint: /bin/bash -c pip3 install -r requirements-dev.txt && make test
