on: push
name: Continuous Integration
jobs:
  test:
    name: docker://python:3.9-slim
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements-dev.txt

    - name: Run tests
      run: make test

    - name: Checks for new endpoints against AWS WAF rules
      uses: cds-snc/notification-utils/actions/waffles@v1
      with:
        app-loc: '${{ github.workspace }}'
        app-libs: '/doc-api-env/Lib/site-packages'
        flask-mod: 'application'
        flask-prop: 'application'
        base-url: 'https://api.document.staging.notification.cdssandbox.xyz'
