on: push
name: Continuous Integration
jobs:
  test:
    name: Continuous integration tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2
    - name: Set up Python 3.9
      uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a # tag=v2
      with:
        python-version: 3.9
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # tag=v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements-dev.txt

    - name: Run tests
      run: make test
    - name: Get python version
      run: |
        python_version=$(python  -V | cut -d' ' -f2)
        echo "python_version=${python_version}" >> $GITHUB_ENV
    - name: Copy site-packages in workspace
      working-directory: /opt/hostedtoolcache/Python/${{ env.python_version }}/x64/lib/python3.9/
      shell: bash
      run: |
        mkdir -p "${{ github.workspace }}/env/" && cp -fR site-packages "${{ github.workspace }}/env/"

    - name: Install development .env file
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        cp -f .env.example .env

    - name: Checks for new endpoints against AWS WAF rules
      uses: cds-snc/notification-utils/.github/actions/waffles@main
      with:
        app-loc: '/github/workspace'
        app-libs: '/github/workspace/env/site-packages'
        flask-mod: 'application'
        flask-prop: 'application'
        base-url: 'https://api.document.staging.notification.cdssandbox.xyz'
